import logging
import json
from uca.core import UCAEngine, AgentMode

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def verify_marketing():
    print("🚀 Starting Marketing Generator Verification...")
    
    try:
        # Initialize Engine
        uca = UCAEngine(mode=AgentMode.STORE_OWNER)
        
        # Process 1 recent article
        print("📰 Processing 1 recent article...")
        results = uca.process_recent_news(limit=1, days=30)
        
        if not results:
            print("❌ No articles found to process.")
            return
            
        result = results[0]
        marketing = result.get('marketing_assets', {})
        
        print("\n✅ Processing Complete!")
        print(f"Source: {result['meta']['source_id']}")
        
        # Check TikTok
        tiktok = marketing.get('tiktok_campaign', {})
        print("\n📱 TikTok Campaign:")
        print(f"   - Hook: {tiktok.get('hook_type')}")
        print(f"   - Caption: {tiktok.get('caption')}")
        print(f"   - Hashtags: {tiktok.get('hashtags')}")
        
        if tiktok.get('hook_type') == "Fallback Hook":
             print("⚠️  Warning: Using Fallback TikTok content (LLM might be failing).")
        else:
             print("✅  TikTok content generated by LLM.")

        # Check SEO
        seo = marketing.get('seo_tags', {})
        print("\n🔍 SEO Tags:")
        print(f"   - Amazon KDP: {len(seo.get('amazon_kdp', []))} tags")
        print(f"   - Etsy: {len(seo.get('etsy', []))} tags")
        
        if "gift idea" in seo.get('amazon_kdp', []) and "trending now" in seo.get('amazon_kdp', []):
             print("⚠️  Warning: Using Fallback SEO tags.")
        else:
             print("✅  SEO tags generated by LLM.")

    except Exception as e:
        print(f"❌ Verification Failed: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    verify_marketing()
